# Riptide-inspired Clippy Configuration
# Enforces our documented coding standards with stricter thresholds

# COMPLEXITY LIMITS - Stricter thresholds for better code quality
# Cognitive complexity is the real measure of function difficulty
cognitive-complexity-threshold = 20
too-many-lines-threshold = 400
too-many-arguments-threshold = 5

# IMPORT DISCIPLINE - Prevent wildcard imports
# Enforces explicit imports to prevent use module::*;
warn-on-all-wildcard-imports = true

# DOCUMENTATION - Public APIs must be documented
missing-docs-in-crate-items = true
