# Rustfmt Configuration
# Conservative settings compatible with stable Rust
# Inspired by Riptide project formatting standards

# Line width and wrapping
max_width = 100
wrap_comments = true
format_code_in_doc_comments = true

# Import organization
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

# Code style preferences
use_field_init_shorthand = true
use_try_shorthand = true
edition = "2021"

# Function and control flow formatting
fn_single_line = false

# Spacing and alignment
spaces_around_ranges = false
space_before_colon = false
space_after_colon = true

# String and array formatting
format_strings = true
normalize_comments = true
normalize_doc_attributes = true

# Advanced formatting
merge_derives = true
reorder_impl_items = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Comment formatting
comment_width = 100
