name: Extended Testing

on:
  workflow_dispatch:
    inputs:
      simulation_iterations:
        description: 'Number of simulation iterations'
        required: false
        default: '1000'
        type: string
      simulation_packets:
        description: 'Number of packets per simulation'
        required: false
        default: '500'
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  extended-simulation:
    name: Extended Simulation Battery
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-extended-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Extended fuzz simulation
      run: |
        cd rohcstar-sim
        cargo run -- fuzz --iterations ${{ github.event.inputs.simulation_iterations }} --packets ${{ github.event.inputs.simulation_packets }}

    - name: Upload simulation results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: extended-simulation-results
        path: rohcstar-sim/rohc_sim_failures.log
        retention-days: 30

  full-benchmark-suite:
    name: Complete Benchmark Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-fullbench-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install benchmark dependencies
      run: sudo apt-get update && sudo apt-get install -y bc

    - name: Run full benchmark suite
      run: |
        cd rohcstar
        chmod +x scripts/run_benchmarks.sh
        ./scripts/run_benchmarks.sh --full --html

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results-${{ github.sha }}
        path: rohcstar/target/criterion/
        retention-days: 30

  cross-platform-test:
    name: Cross-Platform Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-cross-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Run full test suite
      run: cargo test --all --verbose

    - name: Quick simulation check
      run: |
        cd rohcstar-sim
        cargo run -- fuzz --iterations 10 --packets 50
